#!/usr/bin/env python3
"""Build one self-contained FreshRSS theme folder per neutral palette. FreshRSS has no notion of a theme variant: one folder under `p/themes/` is one entry in the picker, all of its `files` load together, and the folder name is the identity FreshRSS stores for a user's selection. So a scheme cannot be a setting inside a theme -- it has to be its own folder, and that folder has to stand on its own, because people copy exactly one of them into their install. Everything those folders share lives in `src/`; the only thing that differs is `_palette.css`, generated here from `palettes/ramps.json`, plus the icons, which carry a baked stroke color an external SVG cannot inherit."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import re
import shutil
import sys


from check_theme import released_version, stylesheet_imports, theme_folder, theme_name


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src"
RAMPS = ROOT / "palettes" / "ramps.json"

# FreshRSS rewrites only the filenames listed in metadata.json to ".rtl.css", with no existence check and no fallback (app/FreshRSS.php), so exactly these two need a mirror on disk. The sources stay direction-neutral -- check_theme.py enforces that -- so each mirror is a verbatim copy.
RTL_MIRRORED = ("atelier.css", "atelier-ui.css")

# A theme folder travels on its own, so it carries the license it is distributed under and the notices for what it bundles.
SHARED_DOCUMENTS = ("LICENSE", "THIRD-PARTY.md")

THEME_FILES = ["_frss.css", "atelier.css", "atelier-ui.css"]
AUTHOR = "mbieh (based on Mapco by Thomas Guesnon)"

# The steps a scheme has to define. 750 is a rung the published ramps do not have; it is derived in the generated file, so every scheme gets the same relationship instead of a hand-picked value.
RAMP_STEPS = (50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950)

# The assets in src/ are painted, not inherited: an external SVG cannot pick up the page's currentColor, and a PNG has no tokens at all. So both are authored in one ramp and re-rendered here in the folder's own. That canonical ramp is Neutral, the one Atelier carries under its own name, so the folder most people install is the one whose assets are carried over verbatim -- and it is read from ramps.json rather than restated as hex, so an asset color is only ever recognised as the step it actually is.
CANONICAL_PALETTE = "neutral"

# The one color in the assets that means something other than a neutral step and stays put in every scheme: the gold of the favorite star, which check_theme.py holds against --favorite.
FIXED_ASSET_COLORS = {"#ad7d09"}
ICON_COLOR = re.compile(r'((?:fill|stroke)=")(#[0-9a-fA-F]{3,6})(")')

PALETTE_HEADER = """/*=== PALETTE: {title} */
/*{underline}*/

/* The neutral ramp, and the only file that differs between Atelier's color schemes: everything else -- the component rules, the semantic roles in _variables.css, the accent hues for success, warning and destructive -- is shared, so this file is what makes the folder {folder} rather than one of its eight siblings. Generated by scripts/build_themes.py from the OKLCH definitions Tailwind 4.3 publishes for "{title}", converted to sRGB because that is the space WCAG contrast is defined in and the one scripts/check_theme.py verifies this ramp in; each step keeps its OKLCH source beside it so the conversion stays auditable. */

:root {{
"""

PALETTE_FOOTER = """

	/* Light surfaces sit above the ramp; white is white in every scheme. */
	--at-scale-white: #fff;

	/* A rung the published ramp does not have. Dark raised surfaces -- row hover, active sidebar entries -- sit between the card at step 800 and step 700, which is already light enough to push secondary text below WCAG AA. Deriving it keeps the relationship identical in every scheme instead of asking each one for a hand-picked value. */
	--at-scale-750: color-mix(in srgb, var(--at-scale-700) 30%, var(--at-scale-800));
}
"""


def shared_partials() -> tuple[str, ...]:
    """The partials atelier.css imports, minus the one this script writes. atelier.css states which partials the theme is made of, and it is the file FreshRSS actually loads, so it is the list rather than a second copy of it here: a partial added to it ships without anyone remembering this script, and one dropped from it stops shipping. The names carry the release query that busts their caches, which is part of the URL and not of the filename."""
    css = (SOURCE / "atelier.css").read_text(encoding="utf-8")
    return tuple(
        target
        for target in (
            name.partition("?")[0] for name in stylesheet_imports(css)
        )
        if target != "_palette.css"
    )


def linear_to_srgb(channel: float) -> float:
    if channel <= 0.0031308:
        return 12.92 * channel
    return 1.055 * (channel ** (1 / 2.4)) - 0.055


def oklch_to_hex(lightness: float, chroma: float, hue: float) -> str:
    """Convert an OKLCH triple to an sRGB hex string. Lightness arrives in percent and hue in degrees, the way Tailwind writes them. Out-of-gamut channels are clipped, which none of the nine neutrals needs -- their chroma peaks at 0.046."""
    light = lightness / 100
    radians = math.radians(hue)
    a = chroma * math.cos(radians)
    b = chroma * math.sin(radians)

    long_ = (light + 0.3963377774 * a + 0.2158037573 * b) ** 3
    medium = (light - 0.1055613458 * a - 0.0638541728 * b) ** 3
    short = (light - 0.0894841775 * a - 1.2914855480 * b) ** 3

    red = 4.0767416621 * long_ - 3.3077115913 * medium + 0.2309699292 * short
    green = -1.2684380046 * long_ + 2.6097574011 * medium - 0.3413193965 * short
    blue = -0.0041960863 * long_ - 0.7034186147 * medium + 1.7076147010 * short

    channels = (
        min(255, max(0, round(255 * linear_to_srgb(channel))))
        for channel in (red, green, blue)
    )
    return "#%02x%02x%02x" % tuple(channels)


def format_oklch(lightness: float, chroma: float, hue: float) -> str:
    """Write the OKLCH source back the way Tailwind states it."""

    def trim(value: float) -> str:
        return f"{value:g}"

    return f"oklch({trim(lightness)}% {trim(chroma)} {trim(hue)})"


def render_palette(scheme: dict, folder: str) -> str:
    title = scheme["title"]
    # The rule under the heading is as wide as the heading, the way every section banner in the theme is written.
    underline = "=" * (len(f"/*=== PALETTE: {title} */") - 4)
    lines = [PALETTE_HEADER.format(title=title, underline=underline, folder=folder)]
    body = []
    for step in RAMP_STEPS:
        lightness, chroma, hue = scheme["steps"][str(step)]
        hex_value = oklch_to_hex(lightness, chroma, hue)
        declaration = f"\t--at-scale-{step}: {hex_value};"
        # The comment column is what makes the ramp readable as a ramp; pad to a fixed width so the OKLCH source lines up across every step.
        body.append(
            f"{declaration:<28}/* {format_oklch(lightness, chroma, hue)} */"
        )
    lines.append("\n".join(body))
    lines.append(PALETTE_FOOTER)
    return "".join(lines)


def render_metadata(scheme: dict, version: str) -> str:
    steps = scheme["steps"]
    light = oklch_to_hex(*steps["100"])
    dark = oklch_to_hex(*steps["900"])
    metadata = {
        "name": theme_name(scheme),
        "author": AUTHOR,
        # Every folder describes itself the same way, down to the palette it carries. The picker lists them side by side, so an entry that ranked itself against the others would be describing folders that are not in front of the reader.
        "description": (
            "Modern light and dark theme inspired by shadcn/ui, on the Tailwind "
            f"{scheme['title']} palette \u2014 {scheme['character']} \u2014 with a "
            "clear reading hierarchy, soft radii, and subtle motion."
        ),
        "version": version,
        "files": THEME_FILES,
        # FreshRSS accepts a light and dark browser theme-color, and the two page backgrounds are what the browser chrome should match.
        "theme-color": {"light": light, "dark": dark},
    }
    rendered = json.dumps(metadata, indent="\t", ensure_ascii=False) + "\n"
    # FreshRSS's own themes keep the file list on one line, and it reads as one thing -- a load order -- rather than three.
    inline = json.dumps(THEME_FILES, ensure_ascii=False)
    return re.sub(r'"files": \[[^\]]*\]', f'"files": {inline}', rendered)


def asset_map(ramp: dict[int, str], canonical: dict[int, str]) -> dict[str, str]:
    """Map every canonical asset color to its counterpart in this ramp."""
    return {canonical[step]: ramp[step] for step in RAMP_STEPS}


def translate_color(value: str, mapping: dict[str, str], source: str) -> str:
    """Look one asset color up, refusing to guess at anything unmapped."""
    value = value.lower()
    if len(value) == 4:
        value = "#" + "".join(channel * 2 for channel in value[1:])
    if value in FIXED_ASSET_COLORS:
        return value
    if value not in mapping:
        raise ValueError(
            f"{source}: {value} is neither a step of the canonical "
            f"{CANONICAL_PALETTE} ramp nor a color that stays fixed across "
            "schemes; the build will not guess what it should become"
        )
    return mapping[value]


def recolor_icon(source: str, mapping: dict[str, str], name: str) -> str:
    """Repaint one SVG's baked colors into the scheme's ramp."""

    def substitute(match: re.Match[str]) -> str:
        value = translate_color(match.group(2), mapping, f"src/icons/{name}")
        return f"{match.group(1)}{value}{match.group(3)}"

    return ICON_COLOR.sub(substitute, source)


def build_scheme(scheme: dict, version: str) -> dict[str, bytes]:
    """Render one theme folder as a path -> bytes mapping, relative to it."""
    folder = theme_folder(scheme)
    ramp = {step: oklch_to_hex(*scheme["steps"][str(step)]) for step in RAMP_STEPS}
    canonical = {
        step: oklch_to_hex(*canonical_scheme()["steps"][str(step)])
        for step in RAMP_STEPS
    }
    mapping = asset_map(ramp, canonical)
    files: dict[str, bytes] = {}

    files["_palette.css"] = render_palette(scheme, folder).encode("utf-8")
    files["metadata.json"] = render_metadata(scheme, version).encode("utf-8")

    for name in shared_partials():
        source = SOURCE / name
        if not source.is_file():
            raise ValueError(
                f"src/atelier.css imports {name}, which src/ does not have"
            )
        files[name] = source.read_bytes()
    for name in RTL_MIRRORED:
        content = (SOURCE / name).read_bytes()
        files[name] = content
        stem, _, suffix = name.rpartition(".")
        files[f"{stem}.rtl.{suffix}"] = content
    for name in SHARED_DOCUMENTS:
        files[name] = (ROOT / name).read_bytes()

    for path in sorted((SOURCE / "icons").iterdir()):
        if path.suffix == ".svg":
            files[f"icons/{path.name}"] = recolor_icon(
                path.read_text(encoding="utf-8"), mapping, path.name
            ).encode("utf-8")
        else:
            files[f"icons/{path.name}"] = path.read_bytes()
    return files


# What a folder holds that the build neither writes nor removes. The previews in the theme picker are drawn by hand, one per palette, and a generated stand-in was only ever a placeholder for them: re-tinting one canonical screenshot cannot show what nine palettes actually look like. The build owns everything else in a folder, so anything it does not produce is reported or pruned -- these are the exception, and the only one.
KEPT_BY_HAND = ("thumbs",)


def is_kept(relative: str) -> bool:
    """Whether a path inside a theme folder is maintained by hand."""
    head = relative.split("/", 1)[0]
    return head in KEPT_BY_HAND


def write_folder(target: Path, files: dict[str, bytes]) -> list[str]:
    """Write the folder and remove whatever the build no longer produces."""
    changed: list[str] = []
    for name, content in sorted(files.items()):
        path = target / name
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_file() and path.read_bytes() == content:
            continue
        path.write_bytes(content)
        changed.append(name)

    expected = set(files)
    for path in sorted(target.rglob("*"), reverse=True):
        relative = path.relative_to(target).as_posix()
        if is_kept(relative):
            continue
        if path.is_dir():
            if not any(item.name != ".DS_Store" for item in path.iterdir()):
                shutil.rmtree(path)
                changed.append(f"{relative}/ (removed)")
        elif relative not in expected:
            path.unlink()
            changed.append(f"{relative} (removed)")
    return changed


def compare_folder(target: Path, files: dict[str, bytes]) -> list[str]:
    """Report every way the folder on disk differs from a fresh build."""
    stale: list[str] = []
    for name, content in sorted(files.items()):
        path = target / name
        if not path.is_file():
            stale.append(f"{target.name}/{name}: missing")
        elif path.read_bytes() != content:
            stale.append(f"{target.name}/{name}: stale")
    if target.is_dir():
        expected = set(files)
        for path in sorted(target.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(target).as_posix()
            if (
                relative not in expected
                and not is_kept(relative)
                and path.name != ".DS_Store"
            ):
                stale.append(f"{target.name}/{relative}: not produced by the build")
    return stale


def load_schemes() -> list[dict]:
    return json.loads(RAMPS.read_text(encoding="utf-8"))["schemes"]


def canonical_scheme() -> dict:
    """The ramp the assets in src/ are authored in."""
    for scheme in load_schemes():
        if scheme["name"] == CANONICAL_PALETTE:
            return scheme
    raise ValueError(f"palettes/ramps.json has no {CANONICAL_PALETTE} scheme")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if a theme folder differs instead of updating it",
    )
    parser.add_argument(
        "--palette",
        action="append",
        help="build only this scheme; repeatable (default: all nine)",
    )
    args = parser.parse_args()

    version = released_version((ROOT / "CHANGELOG.md").read_text(encoding="utf-8"))
    if version is None:
        print("error: CHANGELOG.md has no released version heading", file=sys.stderr)
        return 1

    schemes = load_schemes()
    if args.palette:
        wanted = {name.lower() for name in args.palette}
        schemes = [scheme for scheme in schemes if scheme["name"] in wanted]
        unknown = wanted - {scheme["name"] for scheme in load_schemes()}
        if unknown:
            print(f"error: unknown palette: {', '.join(sorted(unknown))}", file=sys.stderr)
            return 1

    problems: list[str] = []
    for scheme in schemes:
        target = ROOT / theme_folder(scheme)
        try:
            files = build_scheme(scheme, version)
        except ValueError as error:
            problems.append(str(error))
            continue
        if args.check:
            problems.extend(compare_folder(target, files))
        else:
            changed = write_folder(target, files)
            if changed:
                print(f"{target.name}: wrote {len(changed)} file(s)")

    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        if args.check:
            print(
                "error: run scripts/build_themes.py to regenerate the theme folders",
                file=sys.stderr,
            )
        return 1

    if args.check:
        print(f"{len(schemes)} theme folders match a fresh build")
    else:
        print(f"built {len(schemes)} theme folders from src/ and palettes/ramps.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
